name: Deploy React-Server2

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: | 
          npm install
          npm run build

      - name: Build Docker image
        run: |
          docker build -t github-actions-docker-react .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'yangyanyin'
          password: 'yang1187756010'

      - name: Push Docker image
        run: |
          docker tag github-actions-docker-react:latest yangyanyin/github-actions-docker-react:latest
          docker push yangyanying/github-actions-docker-react:latest

