name: Deploy React-Server2

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: | 
          npm install
          npm run build

      - name: Build Docker image
        run: |
          docker build -t github-actions-docker-react .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag github-actions-docker-react:latest yangyanyin/github-actions-docker-react:latest

      - name: Push Docker image
        run: |
          docker push yangyanyin/github-actions-docker-react:latest

      - name: SSH into server and deploy Docker container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: '192.168.44.1'
          username: 'root'
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull yangyanyin/github-actions-docker-react:latest

            docker stop react-server || true
            docker rm react-server || true

            docker run -d -p 5174:5174 --name react-server yangyanyin/github-actions-docker-react:latest